# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8975ccc8965ad6cc605103e432286882b2a383ba3746483fc26033b917633df31ea8e15db0328036e5cc64bece0f39808a735551d0431c8ba51f3c673b4c1362

test:
  secret_key_base: 49ad5b31444946ab40e0d8336bb5c7fccd300063ca647277672de7ded15160525ec7125ec60fdd91777a9daeea0712d1194b6d63c0708d112f446b964607f83a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
